### PR TITLE
Feature/deployment helper events processor deletion

### PR DESCRIPTION
**Pull request by komushi**
# Description

## Type of change

- [ ] *Bug fix (non-breaking change which fixes an issue)*
- [*] *New feature (non-breaking change which adds functionality)*
- [ ] *Breaking change (fix or feature that would cause existing functionality to not work as expected)*
- [ ] *Refactor* (existing code being refactored)
- [ ] *This change requires a documentation update*

# Submission Checklist

- [*] Build Verified
- [*] Bundle Verified
- [*] Lint passing
- [*] Unit tests passing
- [*] Integration tests passing
- [*] Change logs generated

### CODE REVIEW

**Comment by komushi** [comment]
After talking with @bahavar we realize this PR is needed by the customer when a cloudformation stack is to be deleted.

**Comment by boardthatpowder** [comment]
@komushi just realized I had not published my review therefore my above comments related to this PR were not viewable.

**Comment by boardthatpowder** [comment]
Closing due to lack of activity.

**Comment by TusharPatel44** [comment]
@komushi  Can you please provide more information on request above by November 15th.

**Pull request closed without merging**
