### PR TITLE
fix the bug in which relationship is registered without lowercasting …

### PR DESCRIPTION
**Pull request by tsugunao**
…in group create API

# Description

## Type of change

- [*] *Bug fix (non-breaking change which fixes an issue)*
- [ ] *New feature (non-breaking change which adds functionality)*
- [ ] *Breaking change (fix or feature that would cause existing functionality to not work as expected)*
- [ ] *Refactor* (existing code being refactored)
- [ ] *This change requires a documentation update*

# Submission Checklist

- [*] Build Verified
- [*] Bundle Verified
- [*] Lint passing
- [*] Unit tests passing
- [*] Integration tests passing
- [*] Change logs generated 

##### Additional Notes:

This is a bug fix of create group, in which we can create a relation without lower-casting keys and values while other APIs like detachFromGroup has lower-casting inside.

### CODE REVIEW

**Comment by bahavar** [comment]
Please create the change logs by running "rush change"

**Comment by tsugunao** [comment]
created change logs

**Comment by tsugunao** [comment]
added in relationship unit test. Please check.

**Review by bahavar — APPROVED** [review]
changes have been reviewed and tested are ready to be merged

**Pull request merged**
